AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynaMaker QFS and Elfsquad integration (Node.js)

Parameters:
  ElfsquadClientId:
    Type: String
  ElfsquadClientSecret:
    Type: String
  ElfsquadConfiguratorModelId:
    Type: String
  DynamakerApplicationId:
    Type: String
  QfsApiKey:
    Type: String
  QfsEnvironment:
    Type: String
  QfsTaskName:
    Type: String

Globals:
  Function:
    Timeout: 15
    Runtime: nodejs20.x

Resources:
  QFSTaskTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: qfs-task-trigger.handler
      Environment:
        Variables:
          DynamakerApplicationId: !Ref DynamakerApplicationId
          ElfsquadClientId: !Ref ElfsquadClientId
          ElfsquadClientSecret: !Ref ElfsquadClientSecret
          ElfsquadConfiguratorModelId: !Ref ElfsquadConfiguratorModelId
          QfsApiKey: !Ref QfsApiKey
          QfsCallbackFunctionUrl: !GetAtt QFSCallbackFunctionUrl.FunctionUrl
          QfsEnvironment: !Ref QfsEnvironment
          QfsTaskName: !Ref QfsTaskName

  QFSTaskTriggerFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt QFSTaskTrigger.Arn
      Cors:
        AllowMethods:
          - PATCH
        AllowOrigins:
          - 'https://ems.elfsquad.io'

  QFSTaskTriggerFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref QFSTaskTrigger
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

  QFSCallback:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: qfs-callback.handler
      Environment:
        Variables:
          ElfsquadClientId: !Ref ElfsquadClientId
          ElfsquadClientSecret: !Ref ElfsquadClientSecret

  QFSCallbackFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt QFSCallback.Arn

  QFSCallbackFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref QFSCallback
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE

Outputs:
  QFSTaskTriggerFunctionUrl:
    Description: "Lambda function URL for QFSTaskTrigger"
    Value: !GetAtt QFSTaskTriggerFunctionUrl.FunctionUrl